version: "3"

services:

  rails:
    image: dev/rails:5.0.1
    env_file: .env-rails
    ports:
      - '3000:80'
    links:
      - db
      - redis
      - oauth
    volumes:
      - "${PF_PKG}/src/rails/gemfiles:/src/gemfiles:ro"
      - "${PF_PKG}/src/rails/config:/src/rails/config:ro"
      - "${PF_PKG}/opentbl.config.yml:/src/config_files/opentbl.config.yml:ro"
      - "${TM_PKG}/totem.config.yml:/src/config_files/totem.config.yml:ro"
      - "${S_BASE}/thinkspace/api:/src/platform:ro"
      - "${S_BASE}/totem/api:/src/totem:ro"
      - "${S_BASE}/thinkspace/ability:/src/ability:ro"
    environment:
      # ### Seed
      APP_DB_RESET:       'false'
      # APP_DB_RESET:       'true' # 'totem:db:reset[$APP_DB_SEED_DIR] CONFIG=$APP_DB_SEED_CONFIG AI=$APP_DB_SEED_AI'
      APP_DB_SEED_DIR:    ra
      APP_DB_SEED_CONFIG: all
      APP_DB_SEED_AI:     'false'
