version: "3"

services:

  sio:
    image: dev/sio:1.7.3
    env_file: .env-sio
    links:
      - redis
      - rails
    ports:
      - '5555:5555'
    volumes:
      - "${S_BASE}/totem/sio:/src/totem:ro"
      - "${S_BASE}/thinkspace/sio:/src/platform:ro"
      - "${S_BASE}/thinkspace/sio:/src/node:ro"
    environment:
      NODE_ENVIRONMENT: development
