language: ruby
env:
  global:
    - APP_BUNDLE_SRC=./vendor/src
    - APP_INSTALL_API_DIR=$TRAVIS_BUILD_DIR/api
    - APP_INSTALL_CLIENT_DIR=$TRAVIS_BUILD_DIR/client
    - APP_SRC_DIR=$TRAVIS_BUILD_DIR/src
    - APP_LOCAL_DIR=$TRAVIS_BUILD_DIR/local
rvm:
  - 2.3.1
branches:
  only:
    - development
before_install:
  - gem install bundler
  - curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
  - nvm install 6.9.1
  - nvm use 6.9.1
  - npm install -g ember-cli@2.9.1
  - npm install -g bower@1.8.0
  - cd $APP_LOCAL_DIR
install:
  - echo Installing API to $APP_INSTALL_API_DIR
  - "./install.sh --package opentbl/api --install $APP_INSTALL_API_DIR --platform thinkspace"
  - mkdir -p $APP_INSTALL_API_DIR/vendor/src/thinkspace/api
  - mkdir -p $APP_INSTALL_API_DIR/vendor/src/totem/api
  - mkdir -p $APP_INSTALL_API_DIR/.git
  - cp -a $APP_SRC_DIR/thinkspace/api/. $APP_INSTALL_API_DIR/vendor/src/thinkspace/api/
  - cp -a $APP_SRC_DIR/totem/api/. $APP_INSTALL_API_DIR/vendor/src/totem/api/
  - cd $APP_INSTALL_API_DIR
  - echo Bundling with $APP_BUNDLE_SRC
  - bundle install
  - echo Installing CLIENT to $APP_INSTALL_CLIENT_DIR
  - cd $APP_LOCAL_DIR
  - "./install.sh --package opentbl/client --install $APP_INSTALL_CLIENT_DIR --platform thinkspace"
  - cd $APP_INSTALL_CLIENT_DIR
  - ember deploy staging --activate
script:
  - echo Skipping script step...
before_deploy:
  - cd $APP_INSTALL_API_DIR
  - git init
  - git remote add heroku git@heroku.com:opentbl-staging.git
deploy:
  provider: heroku
  skip_cleanup: true
  on: development
  api_key:
    secure: yD0YZCRUrI+gaDv3GyM0oxXKyuwJK3wjsee2MJVbHsokvoYvr3M82c/k7LMvFnndQ/VyLl34bkCZ+u4b0XCUutx+OcrvjHzruSeNf/oObUabPJ2bGHnAVPruAiWLO1uRTLTpXFQYMUKBoLaMYideOU+xqTzFf12u8TIoq2U0/rm8cOaHfIoFejkAHk3Myg8I8nRjXaDbD8xEwc8siUi9ZcDPVj5dNpcSgy/38asB/LLQmzuR1HrXcgJGdG1kCNwUS5zdxlKv8/FX+WuSnIV8jM1jctj7JKhpzhiYT6ZuwoIFK4aTEP9wHEWXBCHqlPLB0y8wWnnFkBuo3O5zHU/kZJzkatWzRy5VZNMtapS7BCasDpnFQ+aegSaeuzGT+i3i8rFcPZxNMVlrU06/vnmqGOvQThshLUOxYkk6vI54XekFrXHfBlMJxsAHutQRSAMSMM3xNweSWhTvfu55zuhi5oSlmEsNlU/nXGVXu5yiXPu8hSiP/fySdQMIEyNCUgYbawRijcw87VUr9IpyBFIvsM4YvZJVSBCLmaSj/BTTAHCNQ956A4JFnbzsBIi0AilrZZ8Ij4pdDdgio7uQI9uEijGPSNgI4vSMNOUpr7Lic81vZUK8gcoShC3N/ko6+YXKXUgvxykipZncPXSjGll8aDS3XVwgoizajE0HjIDxqJc=
  app: opentbl-staging
  run:
    - rails totem:db:production_migrate
    - rails totem:db:domain:load
