language: ruby
env:
  global:
  - APP_BUNDLE_SRC=./vendor/src
  - APP_INSTALL_API_DIR=$TRAVIS_BUILD_DIR/api
  - APP_INSTALL_CLIENT_DIR=$TRAVIS_BUILD_DIR/client
  - APP_SRC_DIR=$TRAVIS_BUILD_DIR/src
  - APP_LOCAL_DIR=$TRAVIS_BUILD_DIR/local
  - APP_TRAVIS_RB=$APP_LOCAL_DIR/travis.rb
rvm:
  - 2.3.1
branches:
  only:
    - feature/travis-merge
before_install:
  - gem install bundler
  - gem install activesupport
  - ruby -r $APP_TRAVIS_RB -e "Travis.before_install"
install:
  - ruby -r $APP_TRAVIS_RB -e "Travis.install"
before_script:
  - ruby -r $APP_TRAVIS_RB -e "Travis.before_script"
script:
  - ruby -r $APP_TRAVIS_RB -e "Travis.script"
before_deploy:
  - gem install dpl
  - ruby -R $APP_TRAVIS_RB -e "Travis.before"
after_deploy:
  - ruby -R $APP_TRAVIS_RB -e "Travis.after_deploy"
