language: ruby

env:
  global:
    - APP_BUNDLE_SRC=./vendor/src
    - APP_INSTALL_DIR=$TRAVIS_BUILD_DIR/opentbl
    - APP_SRC_DIR=$TRAVIS_BUILD_DIR/src

rvm:
  - 2.3.1

before_install:
  - gem install bundler
  - cd local

install:
  - echo Installing to $APP_INSTALL_DIR
  - ./install.sh --package opentbl/api --install $APP_INSTALL_DIR --platform thinkspace
  - mkdir -p $APP_INSTALL_DIR/vendor/src/thinkspace/api
  - mkdir -p $APP_INSTALL_DIR/vendor/src/totem/api
  - cp -a $APP_SRC_DIR/thinkspace/api/. $APP_INSTALL_DIR/vendor/src/thinkspace/api/
  - cp -a $APP_SRC_DIR/totem/api/. $APP_INSTALL_DIR/vendor/src/totem/api/
  - cd $APP_INSTALL_DIR
  - echo Bundling with $APP_BUNDLE_SRC
  - ls -l
  - bundle install

script:
  - echo Skipping script step...

before_deploy:
  - cd $APP_INSTALL_DIR
  - rails railties:install:migrations

deploy:
  provider: heroku
  api_key:
    secure: encrypted-key-here
  app: opentbl-testing
  run:
    - "rails totem:db:production_migrate"
    - "rails totem:db:domain:load"
