language: ruby

env:
  global:
    - APP_BUNDLE_SRC=./vendor/src

rvm:
  - 2.3.1

before_install:
  - echo Building from $TRAVIS_BUILD_DIR
  - gem install bundler
  - cd local

install:
  - ./install.sh --package opentbl/api --install ../../opentbl --platform thinkspace
  - cd ../../
  - cp -a cellar/src/thinkspace/api opentbl/vendor/src/thinkspace/api
  - cp -a cellar/src/totem/api opentbl/vendor/src/totem/api
  - bundle install

script:
  - echo Skipping script step...

before_deploy:
  - cd opentbl
  - rails railties:install:migrations

deploy:
  provider: heroku
  api_key:
    secure: encrypted-key-here
  app: opentbl-testing
  run:
    - "rails totem:db:production_migrate"
    - "rails totem:db:domain:load"
