version: "3"

services:

  ember:
    image: ember-cli/ember:2.8LTS
    volumes:
      - "${PF_PKG}:/src/ember:ro"
      - "${PF_PKG}/app:/${APP_PATH}/app:ro"
      - "${PF_PKG}/config:/${APP_PATH}/config:ro"
      # ###
      - "${PF_SRC}/thinkspace-assets:${MOD_PATH}/thinkspace-assets:ro"
      - "${PF_SRC}/thinkspace-base:${MOD_PATH}/thinkspace-base:ro"
      - "${PF_SRC}/thinkspace-builder:${MOD_PATH}/thinkspace-builder:ro"
      - "${PF_SRC}/thinkspace-builder-pe:${MOD_PATH}/thinkspace-builder-pe:ro"
      - "${PF_SRC}/thinkspace-case:${MOD_PATH}/thinkspace-case:ro"
      - "${PF_SRC}/thinkspace-common:${MOD_PATH}/thinkspace-common:ro"
      - "${PF_SRC}/thinkspace-dock:${MOD_PATH}/thinkspace-dock:ro"
      - "${PF_SRC}/thinkspace-gradebook:${MOD_PATH}/thinkspace-gradebook:ro"
      - "${PF_SRC}/thinkspace-message:${MOD_PATH}/thinkspace-message:ro"
      - "${PF_SRC}/thinkspace-message-pubsub:${MOD_PATH}/thinkspace-message-pubsub:ro"
      - "${PF_SRC}/thinkspace-model:${MOD_PATH}/thinkspace-model:ro"
      - "${PF_SRC}/thinkspace-peer-assessment:${MOD_PATH}/thinkspace-peer-assessment:ro"
      - "${PF_SRC}/thinkspace-peer-assessment-instructor:${MOD_PATH}/thinkspace-peer-assessment-instructor:ro"
      - "${PF_SRC}/thinkspace-peer-assessment-pe:${MOD_PATH}/thinkspace-peer-assessment-pe:ro"
      - "${PF_SRC}/thinkspace-peer-assessment-results:${MOD_PATH}/thinkspace-peer-assessment-results:ro"
      - "${PF_SRC}/thinkspace-phase:${MOD_PATH}/thinkspace-phase:ro"
      - "${PF_SRC}/thinkspace-readiness-assurance:${MOD_PATH}/thinkspace-readiness-assurance:ro"
      - "${PF_SRC}/thinkspace-readiness-assurance-instructor:${MOD_PATH}/thinkspace-readiness-assurance-instructor:ro"
      - "${PF_SRC}/thinkspace-readiness-assurance-irat:${MOD_PATH}/thinkspace-readiness-assurance-irat:ro"
      - "${PF_SRC}/thinkspace-readiness-assurance-trat:${MOD_PATH}/thinkspace-readiness-assurance-trat:ro"
      - "${PF_SRC}/thinkspace-report:${MOD_PATH}/thinkspace-report:ro"
      - "${PF_SRC}/thinkspace-resource:${MOD_PATH}/thinkspace-resource:ro"
      - "${PF_SRC}/thinkspace-space:${MOD_PATH}/thinkspace-space:ro"
      - "${PF_SRC}/thinkspace-toolbar:${MOD_PATH}/thinkspace-toolbar:ro"
      - "${PF_SRC}/thinkspace-user:${MOD_PATH}/thinkspace-user:ro"
      - "${TM_SRC}/totem:${MOD_PATH}/totem:ro"
      - "${TM_SRC}/totem-admin:${MOD_PATH}/totem-admin:ro"
      - "${TM_SRC}/totem-application:${MOD_PATH}/totem-application:ro"
      - "${TM_SRC}/totem-assets:${MOD_PATH}/totem-assets:ro"
      - "${TM_SRC}/totem-base:${MOD_PATH}/totem-base:ro"
      - "${TM_SRC}/totem-config:${MOD_PATH}/totem-config:ro"
      - "${TM_SRC}/totem-engines:${MOD_PATH}/totem-engines:ro"
      - "${TM_SRC}/totem-messages:${MOD_PATH}/totem-messages:ro"
      - "${TM_SRC}/totem-pub-sub:${MOD_PATH}/totem-pub-sub:ro"
      - "${TM_SRC}/totem-simple-auth:${MOD_PATH}/totem-simple-auth:ro"
      - "${TM_SRC}/totem-template-manager:${MOD_PATH}/totem-template-manager:ro"

    networks:
      net:
        ipv4_address: 172.16.66.66

# ### provide static ip for browser bookmarks
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.66.0/24
