version: "3"

services:

  ember:
    image: ember-cli/ember:2.8LTS
    volumes:
      - "${EMBER_SRC}:/src/ember:ro"
      # ### Mounting 'ember-cli/app' and 'ember-cli/config' as directories so watchman will trigger a reload on modifications.
      - "${EMBER_SRC}/app:/${EMBER_APP_PATH}/app:ro"
      - "${EMBER_SRC}/config:/${EMBER_APP_PATH}/config:ro"
      # ###
      - "${EMBER_PLATFORM_SRC}/thinkspace-assets:${EMBER_NODE_PATH}/thinkspace-assets:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-base:${EMBER_NODE_PATH}/thinkspace-base:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-builder:${EMBER_NODE_PATH}/thinkspace-builder:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-builder-pe:${EMBER_NODE_PATH}/thinkspace-builder-pe:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-case:${EMBER_NODE_PATH}/thinkspace-case:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-common:${EMBER_NODE_PATH}/thinkspace-common:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-dock:${EMBER_NODE_PATH}/thinkspace-dock:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-gradebook:${EMBER_NODE_PATH}/thinkspace-gradebook:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-message:${EMBER_NODE_PATH}/thinkspace-message:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-message-pubsub:${EMBER_NODE_PATH}/thinkspace-message-pubsub:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-model:${EMBER_NODE_PATH}/thinkspace-model:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-peer-assessment:${EMBER_NODE_PATH}/thinkspace-peer-assessment:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-peer-assessment-instructor:${EMBER_NODE_PATH}/thinkspace-peer-assessment-instructor:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-peer-assessment-pe:${EMBER_NODE_PATH}/thinkspace-peer-assessment-pe:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-peer-assessment-results:${EMBER_NODE_PATH}/thinkspace-peer-assessment-results:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-phase:${EMBER_NODE_PATH}/thinkspace-phase:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-readiness-assurance:${EMBER_NODE_PATH}/thinkspace-readiness-assurance:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-readiness-assurance-instructor:${EMBER_NODE_PATH}/thinkspace-readiness-assurance-instructor:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-readiness-assurance-irat:${EMBER_NODE_PATH}/thinkspace-readiness-assurance-irat:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-readiness-assurance-trat:${EMBER_NODE_PATH}/thinkspace-readiness-assurance-trat:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-report:${EMBER_NODE_PATH}/thinkspace-report:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-resource:${EMBER_NODE_PATH}/thinkspace-resource:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-space:${EMBER_NODE_PATH}/thinkspace-space:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-toolbar:${EMBER_NODE_PATH}/thinkspace-toolbar:ro"
      - "${EMBER_PLATFORM_SRC}/thinkspace-user:${EMBER_NODE_PATH}/thinkspace-user:ro"
      - "${EMBER_TOTEM_SRC}/totem:${EMBER_NODE_PATH}/totem:ro"
      - "${EMBER_TOTEM_SRC}/totem-admin:${EMBER_NODE_PATH}/totem-admin:ro"
      - "${EMBER_TOTEM_SRC}/totem-application:${EMBER_NODE_PATH}/totem-application:ro"
      - "${EMBER_TOTEM_SRC}/totem-assets:${EMBER_NODE_PATH}/totem-assets:ro"
      - "${EMBER_TOTEM_SRC}/totem-base:${EMBER_NODE_PATH}/totem-base:ro"
      - "${EMBER_TOTEM_SRC}/totem-config:${EMBER_NODE_PATH}/totem-config:ro"
      - "${EMBER_TOTEM_SRC}/totem-engines:${EMBER_NODE_PATH}/totem-engines:ro"
      - "${EMBER_TOTEM_SRC}/totem-messages:${EMBER_NODE_PATH}/totem-messages:ro"
      - "${EMBER_TOTEM_SRC}/totem-pub-sub:${EMBER_NODE_PATH}/totem-pub-sub:ro"
      - "${EMBER_TOTEM_SRC}/totem-simple-auth:${EMBER_NODE_PATH}/totem-simple-auth:ro"
      - "${EMBER_TOTEM_SRC}/totem-template-manager:${EMBER_NODE_PATH}/totem-template-manager:ro"

    networks:
      net:
        ipv4_address: 172.16.66.66

# ### provide static ip for browser bookmarks
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.66.0/24
