default: &DEFAULT

  secret_key_base: "<%=ENV['APP_SECRET_KEY_BASE']%>"

  totem_oauth_providers:
    totem_oauth:
      site:          "<%=ENV['APP_OAUTH_SITE']%>"
      client_id:     "<%=ENV['APP_OAUTH_CLIENT_ID']%>"
      client_secret: "<%=ENV['APP_OAUTH_CLIENT_SECRET']%>"

  aws:
    s3:
      paperclip:
        access_key:        "<%=ENV['APP_AWS_S3_ACCESS_KEY']%>"
        secret_access_key: "<%=ENV['APP_AWS_S3_SECRET_ACCESS_KEY']%>"
        region:            "<%=ENV['APP_AWS_S3_REGION']%>"
        bucket_name:       "<%=ENV['APP_AWS_S3_PAPERCLIP_BUCKET_NAME']%>"

  mailer:
    default:
      from: "<%=ENV['APP_MAILER_FROM']%>"

  smtp:
    postmark:
      username: "<%=ENV['APP_SMTP_POSTMARK_USERNAME']%>"
      password: "<%=ENV['APP_SMTP_POSTMARK_PASSWORD']%>"
      domain:   "<%=ENV['APP_SMTP_POSTMARK_DOMAIN']%>"

  pub_sub:
    url: "<%=ENV['APP_PUBSUB_URL']%>"

  ember:
    platform: "<%=ENV['APP_EMBER_PLATFORM']%>"

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

production:
  <<: *DEFAULT
