variables:
  - &SPACE      import[labs@space]
  - &ASSIGNMENT import[labs@assignment]
  - &TEMPLATE_NAME import[labs@template_name]

spaces:
  - title: *SPACE

space_users:
  - spaces: *SPACE
    users: import[users]

assignments:
  - space: *SPACE
    title: *ASSIGNMENT

phases:
  - assignment: *ASSIGNMENT
    template_name: *TEMPLATE_NAME
    title:         Vet Med Lab
    sections:      
      chart: chart_vet_med

phase_templates: import[labs@phase_templates]

blueprints: import[labs@blueprints]

lab_charts_from_blueprints:
  chart_vet_med:
    title: Lab chart for Vet Med
    categories:
      - title: lab A
        blueprint: category
        results: [blueprint: result_rbc, blueprint: result_hgb, blueprint: result_hct, blueprint: result_mcv, blueprint: result_mcv2, blueprint: result_wbc, blueprint: result_retic]
      - title: lab B
        blueprint: category
        results: [blueprint: result_rbc, blueprint: result_hgb, blueprint: result_hct, blueprint: result_mcv, blueprint: result_mcv2, blueprint: result_wbc, blueprint: result_retic]
