variables:
  oauth_client_id:     '66e57323a61e3380f4391b95577ecd38a42aa33b9d8cec88438405f75025bc86'
  oauth_client_secret: '33379624163cec4b066fa02c273fc23e31da96a4976cd8aefe349123aaf0eac1'
  oauth_site:          http://localhost:3333
  redis_url:           redis://localhost:6379

# # Gemfile
# Which gems to add to the platform's specific Gemfile (e.g. `Gemfile_thinkspace.rb`).
gemfile:
  - "gem 'paperclip'"
  - "gem 'spreadsheet'"
  - "gem 'has_secure_token'"

# ## Application
# What to add to the `config/application.rb` file for Rails.
application_rb:
  - "config.active_job.queue_adapter = :delayed_job"

# Template for the `config/secrets.yml` file for Rails.
secrets:

  development:
    secret_key_base: d01f9aa6064531cbcff49802c38bbfd8e9635643ac8b4c079cc63568d5898c536fa91004af21ad8e09d84562e6bb91fb3d0a990ae56b0aacd0b1e4d1a275b453
    totem_database:
      name:     ts_development
      username: ts_user
      password: password
    totem_oauth_providers:
      totem_oauth_1:
        _config:
          site:   <%=oauth_site%>
          active: true
        opentbl:
          client_id:     <%=oauth_client_id%>
          client_secret: <%=oauth_client_secret%>
          active:        true
    aws:
      sqs:
        access_key:        KEY-GOES-HERE
        secret_access_key: KEY-GOES-HERE
        queue_name:        QUEUE-GOES-HERE
      s3:
        paperclip:
          access_key:        VALUE-HERE
          secret_access_key: VALUE-HERE
          bucket_name:       VALUE-HERE
    discourse:
      username:   USERNAME-HERE
      key:        KEY-HERE
      host:       HOST-HERE
      sso_secret: SSO-SECRET-HERE
      categories:
        support:
          title: testing-support-api
          messages:
            success: Your request has been recieved and we will get back to you as soon as we can.
    smtp:
      postmark:
        username: USERNAME-HERE
        password: PASSWORD-HERE
        domain:   DOMAIN-HERE
    pub_sub:
      url: <%=redis_url%>

  test:
    secret_key_base: 665b6cfe0ab56f2f2a57e8d15d1ec0c28dfe25a2a5b460bec0d53d23ee8bc06eeaec2ccc531d5642a4dcb9f473cd34d443c5b7b103ad400766848517eacc994c
    totem_database:
      name:     ts_test
      username: ts_user
      password: password
    totem_oauth_providers:
      totem_oauth_1:
        _config:
          site:   <%=oauth_site%>
          active: true
        opentbl:
          client_id:     <%=oauth_client_id%>
          client_secret: <%=oauth_client_secret%>
          active:        true
    aws:
      sqs:
        access_key:        KEY-GOES-HERE
        secret_access_key: KEY-GOES-HERE
        queue_name:        QUEUE-GOES-HERE
      s3:
        paperclip:
          access_key:        VALUE-HERE
          secret_access_key: VALUE-HERE
          bucket_name:       VALUE-HERE
    discourse:
      username:   USERNAME-HERE
      key:        KEY-HERE
      host:       HOST-HERE
      sso_secret: SSO-SECRET-HERE
      categories:
        support:
          title: testing-support-api
          messages:
            success: Your request has been recieved and we will get back to you as soon as we can.
    smtp:
      postmark:
        username: USERNAME-HERE
        password: PASSWORD-HERE
        domain:   DOMAIN-HERE
    pub_sub:
      url: <%=redis_url%>

  production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    totem_database:
      name:     "<%= ENV['TOTEM_DATABASE_NAME'] %>"
      username: "<%= ENV['TOTEM_DATABASE_USERNAME'] %>"
      password: "<%= ENV['TOTEM_DATABASE_PASSWORD'] %>"
    totem_oauth_providers:
      totem_oauth_1:
        _config:
          site: https://auth.thinkspace.org
          active: true
        thinkspace:
          client_id:     "<%=ENV['TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_CLIENT_ID']%>"
          client_secret: "<%=ENV['TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_CLIENT_SECRET']%>"
          active:        "<%=ENV['TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_ACTIVE']%>"
    aws:
      sqs:
        access_key:        <%%= ENV['AWS_SQS_ACCESS_KEY'] %>
        secret_access_key: <%%= ENV['AWS_SQS_SECRET_ACCESS_KEY'] %>
        queue_name:        <%%= ENV['AWS_SQS_QUEUE_NAME'] %>
      s3:
        paperclip:
          access_key:        <%%= ENV['AWS_S3_ACCESS_KEY'] %>
          secret_access_key: <%%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
          bucket_name:       <%%= ENV['AWS_S3_PAPERCLIP_BUCKET_NAME'] %>
    redis_url: <%%= ENV['THINKSPACE_REDIS_URL'] %>
    discourse:
      username:   <%%= ENV['DISCOURSE_USERNAME'] %>
      key:        <%%= ENV['DISCOURSE_KEY'] %>
      host:       <%%= ENV['DISCOURSE_HOST'] %>
      sso_secret: <%%= ENV['DISCOURSE_SSO_SECRET'] %>
      categories:
        support:
          title: <%%= ENV['DISCOURSE_CATEGORIES_SUPPORT_TITLE'] %>
          messages:
            success: Your request has been recieved and we will get back to you as soon as we can.
    smtp:
      postmark:
        username: <%%= ENV['SMTP_POSTMARK_USERNAME'] %>
        password: <%%= ENV['SMTP_POSTMARK_PASSWORD'] %>
        domain:   <%%= ENV['SMTP_POSTMARK_DOMAIN'] %>
    pub_sub:
      url: <%%= ENV['PUB_SUB_URL'] %>
