development: &development

  APP_SECRET_KEY_BASE: d01f9aa6064531cbcff49802c38bbfd8e9635643ac8b4c079cc63568d5898c536fa91004af21ad8e09d84562e6bb91fb3d0a990ae56b0aacd0b1e4d1a275b453

  #### Database
  APP_DB_HOST:     localhost
  APP_DB_NAME:     otbl_development
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password

  #### Oauth
  APP_OAUTH_SITE:          http://localhost:3333
  APP_OAUTH_CLIENT_ID:     66e57323a61e3380f4391b95577ecd38a42aa33b9d8cec88438405f75025bc86
  APP_OAUTH_CLIENT_SECRET: 33379624163cec4b066fa02c273fc23e31da96a4976cd8aefe349123aaf0eac1

  #### Redis
  APP_REDIS_URL: &REDIS_URL redis://localhost:6379

  #### Pubsub
  APP_PUBSUB_URL: *REDIS_URL

  #### AWS
  APP_AWS_S3_ACCESS_KEY:
  APP_AWS_S3_SECRET_ACCESS_KEY:
  APP_AWS_S3_PAPERCLIP_BUCKET_NAME:

  #### Mailer
  APP_MAILER_FROM: OpenTBL Support <support@sixthedge.com>

  #### SMTP
  APP_SMTP_POSTMARK_USERNAME:
  APP_SMTP_POSTMARK_PASSWORD:
  APP_SMTP_POSTMARK_DOMAIN:
