prereq_configs: space

variables:
  - &SPACE import[vars@space]
  - &CASE  import[vars@case_readiness_assurance]

  - &PHASE_IRAT IRAT
  - &PHASE_TRAT TRAT

  - &PT_IRAT readiness_assurance_irat
  - &PT_TRAT readiness_assurance_trat

  - pubsub_settings: &PUBSUB_SETTINGS
      pub_sub: true

  - irat_settings: &PS_IRAT
      actions:
        submit:
          class:  ra_irat_submit
          state:  complete
          unlock: next_after_all_ownerables
          auto_score: {score_with: ra_auto_score}
  - trat_settings: &PS_TRAT
      actions:
        submit:
          class:  ra_trat_submit
          unlock: next
          auto_score: {score_with: ra_auto_score}

  - &CAT_COLL collaboration

  - &TEAM_SETS import[teams@all_team_sets]

assignments:
  - {title: *CASE, space: *SPACE, settings: *PUBSUB_SETTINGS}

phases:
  - {title: *PHASE_IRAT, assignment: *CASE, template_name: *PT_IRAT, settings: *PS_IRAT}
  - {title: *PHASE_TRAT, assignment: *CASE, template_name: *PT_TRAT, settings: *PS_TRAT, team_category: *CAT_COLL} # TESTING ONLY
  # - {title: *PHASE_TRAT, assignment: *CASE, template_name: *PT_TRAT, settings: *PS_TRAT, team_category: *CAT_COLL, default_state: locked}

teams:

  team_sets:
    - {space: *SPACE, merge_with: 'import[teams@team_sets]'}

  team_set_teams:
    - {space: *SPACE, merge_with: 'import[teams@team_set_teams]'}

  phase:
    - {title: *PHASE_TRAT, assignment: *CASE, team_sets: *TEAM_SETS, space: *SPACE}

blueprints:
  choices_a: &CHOICES_A
    - {id: a, label: Choice A}
    - {id: b, label: Choice B}
    - {id: c, label: Choice C}
    - {id: d, label: Choice D}
  questions_a: &QUESTIONS_A
    - {id: ra_1_1, question: Question 1, choices: *CHOICES_A}
    - {id: ra_1_2, question: Question 2, choices: *CHOICES_A}
    - {id: ra_1_3, question: Question 3, choices: *CHOICES_A}
  answers_a: &ANSWERS_A
    correct:
      ra_1_1: a
      ra_1_2: b
      ra_1_3: c

readiness_assurance:
  assessments:
    - space: *SPACE
      assignment: *CASE
      phases:     *PHASE_IRAT
      user:       owner_1
      assessment:
        title: IRAT Assessment
        settings:
          ra_type: irat
          submit: {transition_user_team_members_on_last_user_submit: true}
          questions:
            type:   multiple_choice
            random: true
            ifat:   true
          scoring:
            correct:    3
            attempted:  1
            no_answer:  0
            incorrect_attempt: -1
        questions: *QUESTIONS_A
        answers:   *ANSWERS_A
    - space: *SPACE
      assignment: *CASE
      phases:     *PHASE_TRAT
      user:       owner_1
      assessment:
        title: TRAT Assessment
        settings:
          ra_type: trat
          questions:
            type:   multiple_choice
            random: true
            ifat:   true
          scoring:
            correct:   5
            no_answer: 0
            attempted: 1
            incorrect_attempt: -1
        questions: *QUESTIONS_A
        answers:   *ANSWERS_A
